server {
    listen 80;
    server_name localhost;

    # Pastiin root-nya bener ke folder tempat file lu berada
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Ini penting buat Single Page Application (Vue)
        try_files $uri $uri/ /index.html;
    }

    # Kadang Nginx butuh definisi eksplisit buat MIME types
    include /etc/nginx/mime.types;

    # Mastiin folder assets bisa diakses
    location /assets/ {
        alias /usr/share/nginx/html/assets/;
    }
}
